export const FETCH_FAQ_REQUESTED = 'FETCH_FAQ_REQUESTED';
export const FETCH_FAQ_SUCCEEDED = 'FETCH_FAQ_SUCCEEDED';
export const FETCH_FAQ_FAILED = 'FETCH_FAQ_FAILED';
export const FETCH_NEWS_REQUESTED = 'FETCH_NEWS_REQUESTED';
export const FETCH_NEWS_SUCCEEDED = 'FETCH_NEWS_SUCCEEDED';
export const FETCH_NEWS_FAILED = 'FETCH_NEWS_FAILED';
export const SET_LANG = 'SET_LANG';
