-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgVA31uzNzj+SEygNk
YiZeJnlF7e1oLKcBCppYfD4b7t2gCgYIKoZIzj0DAQehRANCAARsPMgl7Z9UxRvC
lF3kZDCHt2vhP+ItGuHKtJwc9e93MkGPnYKGEqcm2VVUltlyxyrXHqdSUga8rwKL
oTSUoxc5
-----END PRIVATE KEY-----