# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'COAktau' do
  
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
 
  pod 'GoogleMaps' 

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
 
  pod  'Firebase/Core'
  pod 'Firebase/Messaging'  

end
