# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'COAktau' do
  
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport' # Include this to enable In-App Devmenu if RN >= 0.43
  ]

   # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
 
  pod 'GoogleMaps' 

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
 
  pod  'Firebase/Core'
  pod 'Firebase/Messaging'  

  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

end
